// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
// // // import type { Metadata } from "next";
// // // import { Geist, Geist_Mono } from "next/font/google";
// // // import "./globals.css";

// // // const geistSans = Geist({
// // //   variable: "--font-geist-sans",
// // //   subsets: ["latin"],
// // // });

// // // const geistMono = Geist_Mono({
// // //   variable: "--font-geist-mono",
// // //   subsets: ["latin"],
// // // });

// // // export const metadata: Metadata = {
// // //   title: "C",
// // //   description: "Generated by create next app",
// // // };

// // // export default function RootLayout({
// // //   children,
// // // }: Readonly<{
// // //   children: React.ReactNode;
// // // }>) {
// // //   return (
// // //     <html lang="en">
// // //       <body
// // //         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
// // //       >
// // //         {children}
// // //       </body>
// // //     </html>
// // //   );
// // // }
// // import type { Metadata } from "next";
// // import { Geist, Geist_Mono } from "next/font/google";
// // import "./globals.css";

// // const geistSans = Geist({
// //   variable: "--font-geist-sans",
// //   subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   variable: "--font-geist-mono",
// //   subsets: ["latin"],
// // });

// // export const metadata: Metadata = {
// //   title: "Hafeez Siddiqui | Automation Developer & Web Developer ",
// //   description:
// //     "Portfolio of Hafeez Siddiqui – Freelance Automation Developer, and specialist in Next.js, React, TypeScript, Sanity, and full-stack solutions. Contact for professional website development and automation services.",
// //   keywords: [
// //     "Hafeez Siddiqui",
// //     "n8n developer",
// //     "Automation Developer",
// //     "Web Developer",
// //     "Next.js Developer",
// //     "Open AI Agents sdk",
// //     "AI Developer",
// //     "Freelancer",
// //     "Full Stack Developer",
// //     "Frontend Developer",
// //     "Website Development",
// //     "Pakistan Developer",
// //   ],
// //   authors: [{ name: "Hafeez Siddiqui", url: "https://www.linkedin.com/in/hafeez-uddin-ahmed-siddiqui" }],
// //   creator: "Hafeez Siddiqui",
// //   publisher: "Hafeez Siddiqui",
// //   openGraph: {
// //     type: "website",
// //     url: "https://yourdomain.com",
// //     title: "Hafeez Siddiqui | Web Developer & Founder of Aura",
// //     description:
// //       "Freelance Web Developer & Founder of Aura. Expert in Next.js, React, TypeScript, and full-stack solutions. Building modern, responsive, and scalable web apps.",
// //     siteName: "Hafeez Siddiqui Portfolio",
// //     images: [
// //       {
// //         url: "https://yourdomain.com/preview.png", // replace with real OG image
// //         width: 1200,
// //         height: 630,
// //         alt: "Hafeez Siddiqui Portfolio",
// //       },
// //     ],
// //   },
// //   twitter: {
// //     card: "summary_large_image",
// //     title: "Hafeez Siddiqui | Web Developer & Founder of Aura",
// //     description:
// //       "Freelance Web Developer specializing in Next.js, React, TypeScript, and full-stack development. Founder of Aura.",
// //     images: ["https://yourdomain.com/preview.png"], // same OG image
// //     creator: "@yourtwitterhandle", // replace when ready
// //   },
// //   metadataBase: new URL("https://yourdomain.com"), // replace with your domain
// //   alternates: {
// //     canonical: "https://yourdomain.com",
// //   },
// //   category: "Portfolio",
// // };

// // export default function RootLayout({
// //   children,
// // }: Readonly<{
// //   children: React.ReactNode;
// // }>) {
// //   return (
// //     <html lang="en">
// //       <body
// //         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
// //       >
// //         {children}
// //       </body>
// //     </html>
// //   );
// // }
// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Hafeez Siddiqui | n8n & Automation Developer",
//   description:
//     "Portfolio of Hafeez Siddiqui — n8n & automation developer, AI developer, Next.js specialist, and OpenAI Agents SDK expert. Explore my projects, skills, and services.",
//   keywords: [
//     "Hafeez Siddiqui",
//     "n8n developer",
//     "automation developer",
//     "AI developer",
//     "Next.js developer",
//     "OpenAI Agents SDK",
//     "workflow automation",
//     "API integration",
//     "chatbots",
//     "serverless apps",
//     "full-stack developer",
//     "automation engineer",
//   ],
//   authors: [{ name: "Hafeez Siddiqui", url: "https://www.hafeezport.vercel.app" }],
//   creator: "Hafeez Siddiqui",
//   publisher: "Hafeez Siddiqui",
//   metadataBase: new URL("https://www.hafeezport.vercel.app"),
//   alternates: {
//     canonical: "https://www.hafeezport.vercel.app",
//   },
//   openGraph: {
//     title: "Hafeez Siddiqui | n8n & Automation Developer",
//     description:
//       "n8n automation developer, AI developer, Next.js developer, and OpenAI Agents SDK expert. Check out my projects and services.",
//     url: "https://www.hafeezport.vercel.app",
//     siteName: "Hafeez Portfolio",
//     // images: [
//     //   {
//     //     url: "./rbg.png", // you can create & add a banner later
//     //     width: 1200,
//     //     height: 630,
//     //     alt: "Hafeez Siddiqui Portfolio",
//     //   },
//     // ],
//     locale: "en_US",
//     type: "website",
//   },
//   twitter: {
//     card: "summary_large_image",
//     title: "Hafeez Siddiqui | n8n & Automation Developer",
//     description:
//       "Explore the portfolio of Hafeez Siddiqui — Automation, AI, Next.js, and OpenAI Agents SDK.",
//     creator: "@HafeezuSiddiqui", // update if you have Twitter
//     // images: ["https://www.hafeezport.vercel.app/og-image.png"],
//   },
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hafeez Siddiqui | n8n & Automation Developer",
  description:
    "Portfolio of Hafeez Siddiqui — n8n & automation developer, AI developer, Next.js specialist, and OpenAI Agents SDK expert. Explore my projects, skills, and services.",
  keywords: [
    "Hafeez Siddiqui",
    "n8n developer",
    "automation developer",
    "AI developer",
    "Next.js developer",
    "OpenAI Agents SDK",
    "workflow automation",
    "API integration",
    "chatbots",
    "serverless apps",
    "full-stack developer",
    "automation engineer",
  ],
  authors: [
    { name: "Hafeez Siddiqui", url: "https://www.hafeezport.vercel.app" },
    {
      name: "LinkedIn",
      url: "https://www.linkedin.com/in/hafeez-uddin-ahmed-siddiqui",
    }, // add LinkedIn link
  ],
  creator: "Hafeez Siddiqui",
  publisher: "Hafeez Siddiqui",
  metadataBase: new URL("https://www.hafeezport.vercel.app"),
  alternates: {
    canonical: "https://www.hafeezport.vercel.app",
  },
  openGraph: {
    title: "Hafeez Siddiqui | n8n & Automation Developer",
    description:
      "n8n automation developer, AI developer, Next.js developer, and OpenAI Agents SDK expert. Check out my projects and services.",
    url: "https://www.hafeezport.vercel.app",
    siteName: "Hafeez Portfolio",
    // images: [
    //   {
    //     url: "https://www.hafeezport.vercel.app/og-image.png",
    //     width: 1200,
    //     height: 630,
    //     alt: "Hafeez Siddiqui Portfolio",
    //   },
    // ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Hafeez Siddiqui | n8n & Automation Developer",
    description:
      "Explore the portfolio of Hafeez Siddiqui — Automation, AI, Next.js, and OpenAI Agents SDK.",
    creator: "@HafeezuSiddiqui",
    // images: ["https://www.hafeezport.vercel.app/og-image.png"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
